"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0q5opah=z*teyd#5v)d-5*j3x8=8c4=*vl)0g_n!6jrxw2h**b'

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production for security
# In development, set to True for debugging
DEBUG = True

# In production, set ALLOWED_HOSTS to your domain(s)
# Example: ALLOWED_HOSTS = ['example.com', 'www.example.com']
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom Content Security Policy middleware
    # Adds CSP headers to prevent XSS attacks
    'bookshelf.middleware.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# These settings enhance the security of your Django application
# IMPORTANT: Some settings should only be enabled in production (when DEBUG=False)

# Browser Security Headers
# SECURE_BROWSER_XSS_FILTER: Enables browser's XSS filtering
# This helps protect against cross-site scripting (XSS) attacks
SECURE_BROWSER_XSS_FILTER = True

# X_FRAME_OPTIONS: Prevents clickjacking attacks by controlling iframe embedding
# Options: 'DENY', 'SAMEORIGIN', or 'ALLOW-FROM'
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents MIME type sniffing
# This prevents browsers from trying to guess content types, reducing XSS risks
SECURE_CONTENT_TYPE_NOSNIFF = True

# Cookie Security Settings
# These should be set to True in production when using HTTPS
# CSRF_COOKIE_SECURE: Ensures CSRF cookies are only sent over HTTPS
# Set to True in production, False in development (unless using HTTPS locally)
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS

# SESSION_COOKIE_SECURE: Ensures session cookies are only sent over HTTPS
# Set to True in production, False in development (unless using HTTPS locally)
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Additional Security Settings
# CSRF_COOKIE_HTTPONLY: Prevents JavaScript access to CSRF cookie
CSRF_COOKIE_HTTPONLY = True

# SESSION_COOKIE_HTTPONLY: Prevents JavaScript access to session cookie
SESSION_COOKIE_HTTPONLY = True

# SESSION_COOKIE_SAMESITE: Controls when cookies are sent with cross-site requests
# Options: 'Strict', 'Lax', or 'None'
SESSION_COOKIE_SAMESITE = 'Lax'

# SECURE_SSL_REDIRECT: Redirects all HTTP requests to HTTPS (production only)
# Set to True in production, False in development
SECURE_SSL_REDIRECT = False  # Set to True in production

# SECURE_HSTS_SECONDS: HTTP Strict Transport Security (HSTS) duration
# Only enable in production with HTTPS
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# SECURE_PROXY_SSL_HEADER: Required when Django is behind a proxy/load balancer
# that handles SSL termination. The proxy sets HTTP_X_FORWARDED_PROTO header.
# Only enable this if you're behind a trusted proxy!
# Format: ('HTTP_HEADER_NAME', 'header_value')
# Example: SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
